export const exactAssets = {
  logo: {
    full: require('./logo/logo-full.png'),
    mark: require('./logo/logo-mark.png'),
  },
  backgrounds: {
    wave: require('./backgrounds/bg-wave-lines.png'),
    vignette: require('./backgrounds/bg-emerald-vignette.png'),
  },
  figures: {
    fit: require('./figures/body-fit.png'),
    bulk: require('./figures/body-bulk.png'),
    lean: require('./figures/body-lean.png'),
    runner: require('./figures/body-fit-runner.png'),
  },
  ui: {
    chartGrowth: require('./ui/chart-growth.png'),
  },
  icons: {
    workout: require('./icons/workout.png'),
    nutrition: require('./icons/nutrition.png'),
    weightLoss: require('./icons/weight_loss.png'),
    faceYoga: require('./icons/face_yoga.png'),
    sleep: require('./icons/sleep.png'),
    aiAssistant: require('./icons/ai_assistant.png'),
    home: require('./icons/tab-home.png'),
    plan: require('./icons/tab-plan.png'),
    progress: require('./icons/tab-progress.png'),
    profile: require('./icons/tab-profile.png'),
    camera: require('./icons/camera.png'),
    upload: require('./icons/upload.png'),
    bell: require('./icons/bell.png'),
    water: require('./icons/water.png'),
    lunch: require('./icons/lunch.png'),
    check: require('./icons/check.png'),
    send: require('./icons/send.png'),
    aiBadge: require('./icons/ai-badge.png'),
    cardio: require('./icons/cardio.png'),
    meal: require('./icons/meal.png'),
    moon: require('./icons/moon.png'),
    face: require('./icons/face.png'),
    chat: require('./icons/chat.png'),
  },
};
